### ISSUE TITLE
RInno Code of Conduct in CRAN README.html 404s

### ISSUE THREAD

**Issue by r-ballard** [ficonsulting/RInno#1]
The link can be found on this page: [https://cran.r-project.org/web/packages/RInno/README.html](cran.r-project RInno) the link in question is labelled "Contributor Code of Conduct".

**Comment by Dripdrop12** [comment]
Thanks for finding that issue!  [This](https://github.com/ficonsulting/RInno/commit/effcd3fdfbd827788c483fe5118adfb65c7312c6) is the fix.
