### ISSUE TITLE
[minor] Binary packages directory naming

### ISSUE THREAD

**Issue by trybik** [ficonsulting/RInno#101]
Nitpicking a bit: the local directory with binary packages should not be called "bin/" which is, by OS conventions, a directory where app's executables live. Following the R installation conventions, "library/" seems best (or "lib/", or "{lib,library}/win.binary/" to stay open for OS X packaging/nativefying) .

**Comment by Dripdrop12** [comment]
Yeah, I agree. Can we do "library/win-binary/"? I only created the bin folder because "library/" is where everything eventually gets installed and I didn't want to create a naming conflict.

**Comment by trybik** [comment]
Right, my bad. Rather best no to nest installation sources into target, so that they can be easily excluded from packaging if necessary (cf. idea of shipping with local R installation #97), so I would vote for "inst/win.binary" (also "inst/source", "inst/mac.binary" etc. when supported).

**Comment by Dripdrop12** [comment]
`pkgs_path` gets you there. This is low enough priority that I'll accept a pull request, but I'm not going to do it myself :-P
