### ISSUE TITLE
StartUp failed with Error

### ISSUE THREAD

**Issue by vikram-rawat** [ficonsulting/RInno#103]
I installed the R 3.5.1 and Node 8.12.0 x64

But after I tried to build a normal app it gives me error like

![image](https://user-images.githubusercontent.com/22342596/46062053-3859fc80-c186-11e8-9d5a-d070071b79e6.png)

I don't know what it is. and how to resolve it. Please look into it.

**Comment by Dripdrop12** [comment]
I apologize for your difficulty - @vikram-rawat. Can you provide a few more details about how you produced this error?

**Comment by vikram-rawat** [comment]
Just to see what is going on I created a basic app with

```
#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)

# Define UI for application that draws a histogram
ui <- fluidPage(
   
   # Application title
   titlePanel("Old Faithful Geyser Data"),
   
   # Sidebar with a slider input for number of bins 
   sidebarLayout(
      sidebarPanel(
         sliderInput("bins",
                     "Number of bins:",
                     min = 1,
                     max = 50,
                     value = 30)
      ),
      
      # Show a plot of the generated distribution
      mainPanel(
         plotOutput("distPlot")
      )
   )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
   
   output$distPlot <- renderPlot({
      # generate bins based on input$bins from ui.R
      x    <- faithful[, 2] 
      bins <- seq(min(x), max(x), length.out = input$bins + 1)
      
      # draw the histogram with the specified number of bins
      hist(x, breaks = bins, col = 'darkgray', border = 'white')
   })
   
   
   if (!interactive()) {
       session$onSessionEnded(function() {
           stopApp()
           q("no")
       })
   }
}

# Run the application 
shinyApp(ui = ui, server = server)


```

But when I run it . It didn't give me that message. It ran but I see just a blank screen. 

![image](https://user-images.githubusercontent.com/22342596/46143925-2efd8c80-c279-11e8-913d-cfc1d7149892.png)


I assume it should have a histogram in there. Some this is not right I don't know what that is.

```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RInno_1.0.1

loaded via a namespace (and not attached):
 [1] compiler_3.5.1  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2 htmltools_0.3.6 tools_3.5.1    
 [7] glue_1.3.0      yaml_2.2.0      Rcpp_0.12.18    rmarkdown_1.10  stringi_1.2.4   knitr_1.20     
[13] digest_0.6.17   jsonlite_1.5    stringr_1.3.1   evaluate_0.11  
```

Please look into it.

**Comment by Dripdrop12** [comment]
remove the last line - 

```
# Run the application 
shinyApp(ui = ui, server = server)
```

RInno runs the app, so if your code starts the app, it starts twice and fails.

**Comment by vikram-rawat** [comment]
I did remove the last line but it didn't help at all. 

I removed the line and I rebuild the entire app from scratch after uninstalling the old one and it still doesn't work. It shows the same blank page.

**Comment by Zac-Pross** [comment]
Hi, I am getting a similar error, even when using the example app. When launching with electron I get a blank window. I'm using R 3.5.1 and installed RInno from Github. It seems that it cannot find the server.R file. Here is the log:

> library path:
> ... C:/Users/ZacPross/Documents/myapp/library 
> 
> working path:
> ... C:/Users/ZacPross/Documents/myapp 
> 
> interactive R session:
> ... FALSE 
> 
> ensuring packages: jsonlite, shiny, magrittr
> 
> Attaching package: 'shiny'
> 
> The following object is masked from 'package:jsonlite':
> 
>     validate
> 
> 
> R version 3.5.1 (2018-07-02) -- "Feather Spray"
> Copyright (C) 2018 The R Foundation for Statistical Computing
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> 
> R is free software and comes with ABSOLUTELY NO WARRANTY.
> You are welcome to redistribute it under certain conditions.
> Type 'license()' or 'licence()' for distribution details.
> 
>   Natural language support but running in an English locale
> 
> R is a collaborative project with many contributors.
> Type 'contributors()' for more information and
> 'citation()' on how to cite R or R packages in publications.
> 
> Type 'demo()' for some demos, 'help()' for on-line help, or
> 'help.start()' for an HTML browser interface to help.
> Type 'q()' to quit R.
> 
> > .libPaths(c('C:/Users/ZacPross/Documents/myapp/library', .libPaths())); shiny::runApp('./', port=1984)
> Error in shinyAppDir(x) : App dir must contain either app.R or server.R.
> Calls: <Anonymous> ... as.shiny.appobj -> as.shiny.appobj.character -> shinyAppDir
> Execution halted


Likewise, if trying to launch with chrome, firefox or ie, server.R still can't be found. Here's the log when launching with chrome:

> library path:
> ... C:/Users/ZacPross/Documents/myapp/library 
> 
> working path:
> ... C:/Users/ZacPross/Documents/myapp 
> 
> interactive R session:
> ... FALSE 
> 
> ensuring packages: jsonlite, shiny, magrittr
> 
> Attaching package: 'shiny'
> 
> The following object is masked from 'package:jsonlite':
> 
>     validate
> 
> Startup failed with error(s):
> 
> App dir must contain either app.R or server.R.

**Comment by Zac-Pross** [comment]
Ok, so I solved this by copy+pasting the server.R, ui.R and global.R (and images etc) into the folder of the installed app manually. Is this expected behaviour? I would expect that these files should get pulled through automatically?
