### ISSUE TITLE
Extensions not working with electron UI

### ISSUE THREAD

**Issue by Tebatu** [ficonsulting/RInno#104]
Hi, great work on implementing a standalone UI!

Unfortunately, some features as the dynamic font scaling (although as I understand, the font size can be set in electron) or data download buttons using the extension "Buttons" in "DT" package do not work yet in the electron UI.
Is it possible to start the app in firefox or chrome like before?

**Comment by Dripdrop12** [comment]
Yep! user_browser = “chrome”. Can you break out the extensions as separate issues so we can tackle them on at a time? Thanks!

**Comment by Dripdrop12** [comment]
Yep! ‘user_browser = “chrome”’

On Sep 26, 2018, at 5:12 AM, Tebatu <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, great work on implementing a standalone UI!

Unfortunately, some features as the dynamic font scaling (although as I understand, the font size can be set in electron) or data download buttons using the extension "Buttons" in "DT" package do not work yet in the electron UI.
Is it possible to start the app in firefox or chrome like before?

**Comment by Tebatu** [comment]
Great! Thanks for the rapid response

**Comment by Dripdrop12** [comment]
Cool, I'll close this out because people can handle it with `user_browser`, but address the specific issues with electron separately.
