### ISSUE TITLE
Unable to create an app because of Error in utils::packageVersion(x) : package ‘fansi’ not found

### ISSUE THREAD

**Issue by turqoisehat** [ficonsulting/RInno#109]
Hello,

Using Windows 10 and R 3.5.1 I am unable to create apps due to the following error:

Error in utils::packageVersion(x) : package ‘fansi’ not found

I have installed fansi, re-installed fansi, I don't know what to do.

**Comment by Dripdrop12** [comment]
hmm, this is a weird issue. I'll try to replicate it on my end

**Comment by turqoisehat** [comment]
The original problems aren't happening, but various versions of a similar problem do happen. I have tried to follow some advice of another poster for a different problem, now I am getting these errors about RInno wanting to "upgrade" my packages by downgrading them:

The following installed packages differ from those downloaded from https://cran.rstudio.com: 
 - dplyr: 	0.7.6 (downloaded) 	0.7.7 (installed)

 - MASS: 	7.3.50 (downloaded) 	7.3.51 (installed)

 - pkgbuild: 	1.0.1 (downloaded) 	1.0.2 (installed)

 - ps: 	1.1.0 (downloaded) 	1.2.0 (installed)

 - stringi: 	1.1.7 (downloaded) 	1.2.4 (installed)

It is recommended that you update these packages. Would you like to do so now? 

1: Yes
2: No
