### ISSUE TITLE
install_github("ficonsulting/RInno") gives error "Found continuation line starting '    person("Jon", "H...' at begin of record.

### ISSUE THREAD

**Issue by EasterBeagle** [ficonsulting/RInno#111]
was trying to get started, ran 
install_github("ficonsulting/RInno") 

and got error "Found continuation line starting '    person("Jon", "H...' at begin of record."

I've never seen anything like that before. Any ideas? TIA

**Comment by Dripdrop12** [comment]
I'm unable to reproduce this error? Is anyone else getting this?

**Comment by martindut** [comment]
I'm also getting this error.
Error in read.dcf(path) : 
  Found continuation line starting '    person("Jon", "H ...' at begin of record.

Should I provide more info?

**Comment by Khillo81** [comment]
I can confirm that I get this error on R 3.4.4 and Windows 10 1809:
`Error in read.dcf(path): Found continuation line starting '        person ("Jon", "H …" at begin of record.`

**Comment by samuelkordik** [comment]
I can confirm this error on R3.5.1 and Windows 10 1511. Same error message.

**Comment by chasemc** [comment]
Looks like this was an issue in the `remotes` package which is a dependency of devtools.  
see: https://github.com/r-lib/devtools/issues/1900#issuecomment-453577160

and was fixed: https://github.com/r-lib/remotes/commit/e56a41e1d0cad55cbe7d60b274b99ab7b7a76b5c


Downloading the below version of `remotes` or a later commit of it should hopefully resolves this issue.
```r
devtools::install_github("r-lib/remotes@dedcc06")

```

**Comment by chasemc** [comment]
Even with suggestions in my earlier comment, it still fails. Submitting PR now.
