### ISSUE TITLE
Error in startServer(host, port, handlerManager$createHttpuvApp()) :    Failed to create server

### ISSUE THREAD

**Issue by Taogreen** [ficonsulting/RInno#114]
Hi I got a error when I used RInno to publish my shiny app, it was okay to get a desktop icon, but when I started up it, I got a error in my log: 

> .libPaths(c('C:/Users/wdeng/Documents/shinyapp/library', .libPaths())); shiny::runApp('./', port=1984)
Loading required package: shiny

Listening on http://127.0.0.1:1984
createTcpServer: address already in use
Error in startServer(host, port, handlerManager$createHttpuvApp()) : 
  Failed to create server
Calls: <Anonymous> -> startApp -> startServer
Startup failed with error(s):

**Comment by Dripdrop12** [comment]
duplicates #102. It fails because port 1984 is already in use. We're working on a hotfix so you can change the port - #113
