### ISSUE TITLE
compile_iss() cannot compile all exe files in python virtual environment

### ISSUE THREAD

**Issue by Taogreen** [ficonsulting/RInno#115]
I use RInno to publish my shiny app which needs to use python scripts, so I include my python virtual environment, but all exe files cannot be compiled even the python.exe in venv\scripts.

**Comment by Dripdrop12** [comment]
There is an option to include .exe files explicitly:

```
create_app(
    "myapp",
    "app_dir",
    file_list = c("file1.exe", "file2.exe")
)
```
You can often do something like `file_list = list.files("python_dir", pattern = ".exe")`.

**Comment by Dripdrop12** [comment]
@Taogreen Feel free to re-open this issue if that solution is not working for you.
