### ISSUE TITLE
Startup failed with error(s): argument is of length zero.

### ISSUE THREAD

**Issue by adamrobinson361** [ficonsulting/RInno#12]
HI John, 

As stated on the FI labs website I am having a problem with the package you have developed. 

I have run the following code:

```r


library('RInno')

create_app(
  app_name = "Deployment Tool", 
  app_dir = "Deployment_Tool_Local".
  pkgs = c("shiny", "tidyverse")
  )
compile_iss()

```

Which creates all the necessary files in the projects directory. 

I then installed the program via the setup_Deployment Tool exe in Rinno_Installer folder that was created. 

When I run the package I get the following error:

Startup failed with error(s):

argument is of length zero

Below is the full error log:

```r

library paths:
... C:/Users/arobinson4/Documents/Deployment Tool/library
... C:/Users/arobinson4/OneDrive/Documents/R/win-library/3.3
... C:/Program Files/R/R-3.3.2/library
working path:
... C:/Users/arobinson4/Documents/Deployment Tool
Loading required package: methods
Warning message:
package 'jsonlite' was built under R version 3.3.3 
Warning message:
package 'devtools' was built under R version 3.3.3 
Warning message:
package 'httr' was built under R version 3.3.3 
ensuring packages: jsonlite, shiny, magrittr

Attaching package: 'shiny'

The following object is masked from 'package:jsonlite':

    validate

Warning message:
package 'shiny' was built under R version 3.3.3 
Startup failed with error(s):

argument is of length zero

```

Any help would be appreciated. Please note I get the same error if I use the example app outlined on your blog post here: http://www.ficonsulting.com/filabs/RInno

Am I missing some parameters that don't have defaults?

Kind Regards,

Adam

**Comment by Dripdrop12** [comment]
Hi Adam,

Do you use Chrome? I think this may be related to an issue with the user_browser argument.

Jon

**Comment by adamrobinson361** [comment]
Hi Jon, 

Thanks for your reply. I have chrome installed but use internet explorer as the default browser. 

As per the thread on FI labs I have reinstalled from GitHub but now have a new error:

invalid 'file argument'

I've tested this initially for my app but also for the demo app in your post. 

So the code is:

```r
example_app(app_dir = "app") 
create_app(app_name = "myapp", app_dir = "app")
compile_iss()
```

and the error log is:

```r
trying URL 'http://mirror.its.dal.ca/cran/bin/windows/contrib/3.3/jsonlite_1.5.zip'
Content type 'application/zip' length 1159418 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

package 'jsonlite' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\arobinson4\AppData\Local\Temp\RtmpKYqBkp\downloaded_packages
trying URL 'http://mirror.its.dal.ca/cran/bin/windows/contrib/3.3/devtools_1.13.2.zip'
Content type 'application/zip' length 440518 bytes (430 KB)
==================================================
downloaded 430 KB

package 'devtools' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\arobinson4\AppData\Local\Temp\RtmpKYqBkp\downloaded_packages
trying URL 'http://mirror.its.dal.ca/cran/bin/windows/contrib/3.3/httr_1.2.1.zip'
Content type 'application/zip' length 281488 bytes (274 KB)
==================================================
downloaded 274 KB

package 'httr' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\arobinson4\AppData\Local\Temp\RtmpKYqBkp\downloaded_packages
NULL
library paths:
... C:/Users/arobinson4/OneDrive/Documents/myapp/library
... C:/Users/arobinson4/OneDrive/Documents/R/win-library/3.3
... C:/Program Files/R/R-3.3.2/library
working path:
... C:/Users/arobinson4/OneDrive/Documents/myapp
Loading required package: methods
Warning message:
package 'jsonlite' was built under R version 3.3.3 
Warning message:
package 'devtools' was built under R version 3.3.3 
Warning message:
package 'httr' was built under R version 3.3.3 
ensuring packages: jsonlite, shiny, magrittr

Attaching package: 'shiny'

The following object is masked from 'package:jsonlite':

    validate

Warning message:
package 'shiny' was built under R version 3.3.3 
Startup failed with error(s):

invalid 'file' argument
```

Any help appreciated,

Regards

Adam

**Comment by Dripdrop12** [comment]
```
NULL
library paths:
```
It looks like it is having difficulty with `appwd` and `applibpath`, which are used by "package_manager.R" to ensure your app dependencies have been installed before sourcing "app.R" to kick off your app.

When a NULL gets passed to `source`, it returns `invalid 'file' argument`. Also, can you try installing it in your documents instead of OneDrive? We have not tested installations in OneDrive. It shouldn't make a difference, but I am curious if that has something to do with it.

Best,
Jon

**Comment by adamrobinson361** [comment]
Hi Jon, 

I've installed in my documents folder not on the one drive and had a look around the "package_manaeger.R' file. 

It seems to get in to trouble when it tries to run the app.R file from this code. 

```r
  # App is launched in the system default browser (if FF or Chrome, should work
  # fine, IE needs to be >= 10)
  source(file.path(appwd, "utils/app.R"))
```
Providing the following error: 

```r
Error in file.exists(config$browser) : invalid 'file' argument.
```

I've narrowed the problem down to this part of the if statement:

```r
  } else if (file.exists(config$browser)) {
    # Set the default browser option for shiny apps to manual_browser, so user
    # doesn't get prompted again.
    options(browser = config$browser)
```
I think that the problem is that ```r config$browser ``` is text rather than the object. 

You could fix this by using ```r get(config$browser)``` to refer to the object. 

If I do this in the app.R and run the script the app opens as desires. 

I may be wrong but let me know if you think that's what it is.

Regards

Adam

**Comment by Dripdrop12** [comment]
Can you provide your `utils/config.cfg` file? It looks like there may be a `character(0)` assigned to your browser argument.

**Comment by adamrobinson361** [comment]
Looked into this a bit more and not sure if what I previously said was right. 

The config .cfg file is as follows when installed. At this point the app will not load and I get the error. 

```JSON
{
  "appname": "DeploymentTool",
  "r_bindir": "C:\\Program Files\\R\\R-3.3.2\\bin",
  "pkgs": {
    "pkgs": ["shiny", "tidyverse"],
    "cran": {
      "repo": "http://cran.rstudio.com"
    }
  },
  "logging": {
    "error_log": "error.log"
  },
  "host": "none",
  "app_repo": "none",
  "auth_user": {
    "auth_user": "none"
  },
  "auth_pw": {
    "auth_pw": "none"
  },
  "remotes": {
    "remotes": "none"
  },
  "user_browser": "chrome",
  "flex_file": "none"
}
```

If I change 

```JSON
"user_browser": "chrome",
```

to 

```JSON
"user_browser": "ie",
```

The application runs. I'm not sure where chrome came from originally though as internet explorer is my default browser.

Adam

**Comment by Dripdrop12** [comment]
"chrome" is the default browser because IE often breaks icons, but if you would like to set it up to default to IE, you can modify your `create_app` statement to read:
```
example_app(app_dir = "app") 
create_app(app_name = "myapp", app_dir = "app", user_browser = "ie")
compile_iss()
```

**Comment by adamrobinson361** [comment]
Just tried your suggested code and works perfect for my needs - thanks for your help!

Not sure what the problem is with chrome is. Maybe its just on my computer.

Cheers

Adam

**Comment by Dripdrop12** [comment]
Great! Feel free to let us know if you have any other issues. We are happy to help.
