### ISSUE TITLE
Nodejs is not installed bug

### ISSUE THREAD

**Issue by ryanpfalz** [ficonsulting/RInno#123]
I have nodejs installed (in C:\Program Files\nodejs), and I have added the installation path to the 'PATH' system environment variable (per [https://github.com/ficonsulting/RInno/issues/96](url)).
However, after running
`
  create_app(
    app_name = "TestApp", 
    app_dir  = getwd(),
    pkgs     = c("shiny", "shinyjs", "glue", "rhandsontable"))
`,
I immediately receive the message `Nodejs is not installed...
Would you like to install it? `
If I choose 'Yes', once the .exe is built and installed, I get a dialog box stating `character string expected as first argument` (As shown in issue linked above). Looking for help on sorting out the Nodejs issue, as this seems to be the root of my issues.

**Comment by zoleak** [comment]
I am having the same problem. I noticed you closed the issue. Can you explain how you solved it, if you did? Thanks.
