### ISSUE TITLE
Allow for Github Authentication via Personal Access Token

### ISSUE THREAD

**Issue by samuelkaminsky** [ficonsulting/RInno#17]
The current version of the package allows for authentication to private github repos, but not for accounts that use two factor authentication. It would be helpful to add in authentication to a Github account via an personal access token that could be passed to the `auth_token` argument in `install_github()` as well.

Thanks for all the work on this great package!

**Comment by Dripdrop12** [comment]
I completely agree Sam! @r-ballard is looking into it at the moment, but we would appreciate any suggestions you have. We are preparing for a CRAN release, so it would be great to fit this into that release.  Do you have any experience with oAuth?

Best,
Jon

**Comment by r-ballard** [comment]
Just got the heads up. I've worked with some other packages that utilize the OAuth standard and think some of their function definitions can be repurposed. I'll begin prototyping and see if I can make any progress. @samuelkaminsky if you have any additional insights I'd be glad to read!

**Comment by samuelkaminsky** [comment]
Thanks for the quick response! I don't have any expertise in OAuth, so the only suggestion I'd have would be to include an additional parameter in `create_app()` that would allow you to set a value for a personal access token. That could then either be set as an environmental (`GITHUB_PAT`) for the session or simply be passed to the `auth_token()` argument in `install_github()`.

**Comment by Dripdrop12** [comment]
@samuelkaminsky I just added support for this in the dev branch. Can you try it out and let me know if you are having any difficulty?

```
devtools::install_github("ficonsulting/RInno", ref = "develop")
```

```
create_app("myapp", "app", 
    app_repo_url ="Dripdrop12/RInnoApp", 
    auth_token = "[your token]")
```

Thanks!

**Comment by Dripdrop12** [comment]
I'll re-open this issue if you are still having difficulty Sam, but Sollano was able to successfully use his Github token to update his app. So I'm going to close this out until further notice.

**Comment by samuelkaminsky** [comment]
Hi, apologies for the delay and thanks for implementing this! I just tested it with a private repo and received the error:

`Error in create_config(app_name, app_dir, pkgs, remotes = dots$remotes,  : 
  jetblueairways/JetBluePAA is not a valid app_repo_url.`

I entered the repo url and auth_token the same way I would in `install_github()` and how it was indicated in your comment. When I replace it with the full url to the repository (i.e. including github.com/), `create_app()` runs, however I then get an incorrect password error when i run the installer:

`Error in warn_user(httr::GET(base_url)) : 
  It looks like your username and/or password are incorrect.
Calls: source ... withVisible -> eval -> eval -> get_remote_version -> warn_user
Execution halted`

**Comment by Dripdrop12** [comment]
Yeah, RInno's documentation states that an `app_repo_url` is a "Repository address in the format "https://bitbucket.org/username/repo" (repo = app_name). Only Bitbucket and GitHub repositories are supported."

Can you share your create_app call? And the resultant config.cfg file?
