### ISSUE TITLE
utils\regpaths.json file is not created before deployment

### ISSUE THREAD

**Issue by AlexFainshtein** [ficonsulting/RInno#20]
This is a minor problem, because it does not allow to test the app before the deployment: running <app_name>.bat causes run.js fail in line 25:

`var fRegPaths = oFSO.OpenTextFile('utils\\regpaths.json', 1); // 1 = for reading`

because the file is not found.

**Comment by Dripdrop12** [comment]
Yeah, regpaths.json gets created by the Inno Setup .exe after everything has been compiled.

**Comment by Dripdrop12** [comment]
The information is queried from each computer's registry, so it has to be a run-time test. Compile the .exe and install the app. There should be a utils/regpaths.json file that you can inspect at that time. Give the exe to someone else or run it on another computer, and you should see what gets stored in that json file ;)
