### ISSUE TITLE
Option for a standalone UI

### ISSUE THREAD

**Issue by trybik** [ficonsulting/RInno#21]
The package does a great job at what it is designed for (hides complexity of packaging R Shiny standalone app). It would be great to add to it option to ask for a standalone UI, instead of using a browser tab/window. The possible approaches I can think of, from the easiest to the most difficult,  are:

1. use Chrome with `--app=URL` switch, and make it install system-wide if not avail, like R or Pandoc are now; beware: Chrome is apparently dropping support for the stand-alone apps,
2. in a browser-indpendent fashion plug-in JavaScript like `window.open(APP_URL, APP_NAME, "menubar=no,toolbar=no,location=no")` in some point, but also make sure that the default like previously opened tabs, or home page do not open (and are not lost for when user re-opens the browser)
3. use portable UI solution like previously ChromePortable (discontinued and problematic), or, better, Electron

**Comment by Dripdrop12** [comment]
This is an awesome suggestion. I like the 3rd option, but I have never used Electron. It looks like you have found me a weekend activity @trybik ;)

**Comment by trybik** [comment]
I have no idea if it's possible for R Shiny to view an Electron local app as a browser - would be great, but I would still welcome the non-conflicting, "easy" solution 1 (+/- avoiding passing the URL in runApp directly after "chrome.exe app=", i.e. w/o space).

**Comment by Dripdrop12** [comment]
Easy it is ;) I think that electron is a bit overkill when all we need is a browser

**Comment by trybik** [comment]
That's great, but wouldn't it be really great with `create_app( ..., include_Chrome = FALSE)` flag for if your users need Chrome installed? :)

**Comment by Dripdrop12** [comment]
You mean `create_app(..., include_Chrome = TRUE)`?? ;)

**Comment by trybik** [comment]
No, I meant `FALSE` as a default value for `create_app` function, like the [`use_R` option](https://github.com/ficonsulting/RInno/blob/master/R/create_app.R#L48), but, yes, I would like to be able to use it with `TRUE` value, such that it then calls `get_Chrome(app_dir, Chrome_version)` :)

**Comment by Dripdrop12** [comment]
touché

**Comment by Dripdrop12** [comment]
@trybik I got a shiny app running in Electron this week... ;) I'd like to figure out how to port the process in the installation, including node.js and electron. Thank you for the inspiration here! Also, let me know if you're interested in building this into the next release.

**Comment by trybik** [comment]
Kudos! From my side there is no rush - until June I would not use/test the Electron build. Starting in June I would definitively be interested in testing it with my RShiny app.

**Comment by Dripdrop12** [comment]
@trybik We just got a clean Electron build and run cycle on the develop branch. I'd love it if you give it a try and create other issues with any Electron integrations you'd like to see us focus on as we get ready for the first release with a full stand-alone UI release.

**Comment by trybik** [comment]
That's great! I will give it a spin and let you know. This should happen within next month.
