### ISSUE TITLE
Opinion about continuous installation

### ISSUE THREAD

**Issue by zhengle-advantaseeds** [ficonsulting/RInno#22]
The package(v.0.1.0) did a great job. In the continuous installation option, it would be useful that the app sync to the online repository when the internet available. Otherwise, the app will start without updating if the internet unavailable. Thanks

**Comment by zhengle-advantaseeds** [comment]
Here is the solution I proposed for it:
In ./utils/package_manager.R
add `"RCurl"` to `init_pkgs`

In ./utils/get_app_from_app_url.R
modify the get_remote_version by adding:
`get_remote_version = function(...){
 if(!RCurl::url.exists('www.bitbucket.org'))return('none')
...
}`

In ./utils/ensure.R
modify the cran_pkg_version by adding:
`cran_pkg_version = function(pkg, cran_url){
if(RCurl::url.exists(cran_url)){
  ...
} else {
  packageVersion(pkg)
}
}`

**Comment by Dripdrop12** [comment]
What do you think about this simple ping wrapper?
```
ping_site <- function(site_url) {
  !as.logical(system(paste("ping -n 1", site_url)))
}
```
I am thinking we can just ping "www.google.com" once. If the ping fails, don't install anything and just load packages. I'll push a commit tonight.

**Comment by Dripdrop12** [comment]
I'd like to reduce the number of package dependencies, and there is a catch-22 here. If we use RCurl to test our internet connection, we still have to install it from the internet. ping is always available to us ;)

**Comment by Dripdrop12** [comment]
Check out commit 1dd34f0282b729591a9dab00bcbb553852508293

**Comment by rareaquaticbadger** [comment]
Hi there,

Really liking this package!  Currently though, I can't run the example_app as I'm getting a "Please connect to the internet and try again" message. 

I'm not 100% sure, but I think this may be to be due to our company firewall not allowing pings, and it's something I can't seem change without admin privileges.  Is there a logical option to ignore your `ping_site()` wrapper? 

zhengle-advantaseeds RCurl solution works for me: `RCurl::url.exists('www.google.com')` returns TRUE, but `ping_site("www.google.com")` is returning FALSE.

**Comment by Dripdrop12** [comment]
@zhengle-advantaseeds is pretty smart, so I'm not surprised. How about we add an option to ping or use `RCurl` for the internet connection check? Would you like that solution?

**Comment by rareaquaticbadger** [comment]
Hi @Dripdrop12, yes, that would be great!  Either an option to use `RCurl` or just to disable the ping check would be useful for those of us with overly restrictive firewall settings.

Thanks!

**Comment by zhengle-advantaseeds** [comment]
I think @Dripdrop12's ping_site is faster; because it does not require another package. Maybe we can dig into the RCurl package to extract the url.exists function and integrate into the RInno package.

**Comment by Dripdrop12** [comment]
@rareaquaticbadger does `!httr::http_error("www.google.com")` work for you? We are already using httr, and it seems to accomplish what we need from `ping_site`

**Comment by Dripdrop12** [comment]
@rareaquaticbadger Please re-open the issue if `httr::http_error` is not going to work for you; we've switched it over, and I hope that works for you!
