### ISSUE TITLE
Failure with Chrome (only)

### ISSUE THREAD

**Issue by dmenne** [ficonsulting/RInno#23]
Using Windows 10/64bit, German Version, RInno as of today from github. Default Browsers is Firefox, Chrome and Edge installed and working (this is a developer's machine)

Running the default installation of the sample app, no user_browser given: Chrome starts, no page displayed  (black background), and ----- scary ------: all my extensions are disabled, popping up one after the other slowly like popcorn. I have never seen this before. (Added on edit): and the myapp directory is locked, need to restart.

Using user_browser = "firefox", "ie", or even "blub" starts firefox, and shiny runs ok. user_browser="chrome" gives the same as the default above.

**Comment by dmenne** [comment]
Error message when chrome is browser
```
Listening on http://127.0.0.1:5316
[5568:3168:0918/182732.914:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
[5568:6944:0918/182732.961:ERROR:external_registry_loader_win.cc(147)] File C:\Users\Dieter\AppData\Local\CRE\iokhogohoamdhejdbenjbjkhjmjlggab.crx for key Software\Google\Chrome\Extensions\iokhogohoamdhejdbenjbjkhjmjlggab does not exist or is not readable.
[5568:6944:0918/182732.961:ERROR:external_registry_loader_win.cc(147)] File C:\Program Files (x86)\OpenApp\chromeaddon.crx for key Software\Google\Chrome\Extensions\kincjchfokkeneeofpeefomkikfkiedl does not exist or is not readable.

```

**Comment by Dripdrop12** [comment]
The only thing that RInno does with the `user_browser` argument is control the shiny browser option, so this is pretty strange behavior. Here are the steps it takes:

1. It checks the "Software\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe" registry entry for Chrome's installation path
2. It writes the query to "utils/regpaths.json"
3. It sets options(browser = "<Chrome path from step 2>")
4. And finally, `shiny::runApp("./", launch.browser = T)`

In the app's installation directory, there should be a file called "utils/regpaths.json." Can you take a look at your Chrome installation and make sure the Chrome path is what you would expect? There is a chance that the registry check is returning the wrong path for Chrome.

**Comment by dmenne** [comment]
Thanks for you comments. Sorry that I did not follow up on this, the problem with virus checkers (which are understandable, but nasty) and the scary behavior that the extensions are disabled made me think over the concept. I had hoped that I could give this to hospital IT who is very defensive when it comes to external programs, or online stuff. But it looks like your creative RInno app might be causing more problems.

I hope that the Docker method is less intrusive, but getting hospital IT to install Docker is also a major undertaking. 

For the example, see https://hub.docker.com/r/dmenne/gastro-docker/

**Comment by Dripdrop12** [comment]
@dmenne Can you explain what is less intrusive than setting the browser option based on the browser's installation path? Or provide some more information about the issue you are having? I would be very happy to help you trouble shoot this problem. 

However, I assure you. RInno does **not** touch your browser's addIns, and I am a bit confused about your reference to virus checkers...

**Comment by dmenne** [comment]
For me such changes would be ok, but when I think of giving this to hospital It, and anything happens to the browser (being correctly or incorrectly installed), I lose my job. No kidding.

The virus-checkers problem is not your's: Norton sees an installation file that has no users, and immediately deletes the file. This happens to all unsigned stuff, but Inno (not only RInno) has a high penalty that is difficult to workaround, because often malware uses Inno.

**Comment by Dripdrop12** [comment]
Well, just to clarify. RInno does not do anything with the browser. It just looks for it so that Shiny can launch. 

If someone would fire you because they broke their own browser and then blamed you for it, that is terrible management and it would be entirely without cause. Furthermore, a simple google search on the relationship between Inno Setup and malware yields a few reports (10 years ago) of false positives on unsigned Inno .exe files but nothing on the first page of malware created with Inno Setup. Feel free to share references to this issue because I take your statement about the security risk extremely seriously. Thanks!

**Comment by Dripdrop12** [comment]
@dmenne I was able to replicate the error message here with the Chromium browser. It looks like Chromium has different scripting options (i.e. kiosk mode instead of app mode). I was getting the same error above when running a shiny app with Chromium in app mode (which does not exist). Do you have Chromium installed on your development computer or Chrome?

**Comment by dmenne** [comment]
Chrome windows 10 German. Current updateAm 23.09.2017 03:23 schrieb Jonathan Hill <notifications@github.com>:@dmenne I was able to replicate the error message here with the Chromium browser. It looks like Chromium has different scripting options (i.e. kiosk mode instead of app mode). I was getting the same error above when running a shiny app with Chromium in app mode (which does not exist). Do you have Chromium installed on your development computer or Chrome?

**Comment by zhengle-advantaseeds** [comment]
One of the computers I used for testing the program experienced the crush on chrome as well. However, if I change the config.cfg as the following:
Before editing: ```"user_browser": "chrome", ```
After editing: ```"user_browser": "IE", ```
And then, the magic happened: The app will run on chrome without error. lol...

**Comment by Dripdrop12** [comment]
@zhengle-advantaseeds that is an awesome test. The best explanation is that the registry check is finding the wrong version of Chrome because R is case sensitive and "IE" will fail the "ie" check and cause it to default back to the default browser. If it opens in Chrome without error, that means the default must be something different then the registry check. You inadvertently solved the mystery here!

**Comment by Dripdrop12** [comment]
Can you send me the first three lines of `sessionInfo()`?

**Comment by zhengle-advantaseeds** [comment]
Here is the info:
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 15063)
Thank you!

**Comment by dmenne** [comment]
same for me

**Comment by zhengle-advantaseeds** [comment]
![error](https://user-images.githubusercontent.com/30634290/31126531-b4b51b6e-a811-11e7-8712-9eb51e0a40f4.jpg)
Here is the screenshot of the chrome.

**Comment by Dripdrop12** [comment]
How about the contents of `utils/regpaths.json`? I think it has something to do with the 32-bit machines you guys are using. My dev laptop is a 64-bit windows 7 machine, but there is an exception in the default shiny option for 32-bit machines:

https://github.com/rstudio/rstudio/blob/master/src/cpp/r/session/RSession.cpp (line #1004)

**Comment by dmenne** [comment]
No, that's not 32 bit, it's 64. MingW has 32 bit tools added, but that's not the machine

**Comment by zhengle-advantaseeds** [comment]
Here is the information from the utils/regpaths.json:
```
{
"r": "C:\\Program Files\\R\\R-3.4.1",
"chrome": "C:\\Program Files (x86)\\Google\\Chrome\\Application",
"ie": "C:\\Program Files\\Internet Explorer\\IEXPLORE.EXE",
"ff": "none",
"pandoc": "none"
}
```

**Comment by Nadhir10** [comment]
Yesterday I comiled my first RInno app and it worked well, but today I had the same problem on chrome (exactly similar to @zhengle-advantaseeds description and answers). 
I can see form task-manager that R sessions are launched but chrome is blank (which remain active even if you close the browser, I need to end them manually to be able to restart the app)
I wanted to add that after many tests I noticed that my app started normally when chrome was already launched.

**Comment by Dripdrop12** [comment]
@Nadhir10 did you add the [server.R](https://github.com/ficonsulting/RInno#serverr-requirements) code to your app to close R sessions when the browser closes?

**Comment by Nadhir10** [comment]
@Dripdrop12 , yes I did :
  session$onSessionEnded(function() {
    stopApp()
    q("no")

**Comment by Dripdrop12** [comment]
I believe I may have finally figured this out. I added `ArchitecturesInstallIn64BitMode = x64` to the .iss

This defaults to x64 and falls back on x86. The installer was defaulting to x86 before and it may have been causing this bug. Let me know if you are still experiencing it post `Version: 0.2.0`
