### ISSUE TITLE
exe files missing after compiling

### ISSUE THREAD

**Issue by chasemc** [ficonsulting/RInno#25]
I have a dependency on an command line tool executable .exe that is called from shiny. RInno transfers everything really nicely... except any .exe files. Any thoughts on a fix?

**Comment by Dripdrop12** [comment]
Yep, .exe files are handled differently because all the others are incorporated into the installation process (R, Pandoc, etc). Let me take a quick look at this.

**Comment by Dripdrop12** [comment]
You can try adding the command line tools to `file_list`, which should put them in your shiny app's root directory:

```
create_app("myapp", "app", file_list = "<path to command line tool>")
```
Let me know if that works for you!

**Comment by Dripdrop12** [comment]
@chasemc let me know if this works for you!

**Comment by chasemc** [comment]
Thanks for the help, it worked!  As a note in case someone else comes across this: you can assign a vector of files to file_list if you have multiple.

**Comment by Dripdrop12** [comment]
Yep, I vectorized the transformation into Inno Setup's scripting language :)
