### ISSUE TITLE
I get this error when I run the .exe file.

### ISSUE THREAD

**Issue by vikram-rawat** [ficonsulting/RInno#26]
![image](https://user-images.githubusercontent.com/22342596/31112121-92bcc50c-a82f-11e7-89df-8d0ea847df06.png)

I really want to know how to use this setup properly there is just isn't documentation to help us. It needs more explanation.

**Comment by vikram-rawat** [comment]
I love your concept it's very very nice. I never knew I could I could create an Executable with R code. It will reduce my job of automation in VBA to near 0%.

But So Far I was not able to figure out how to run it even on my own computer. A very good concept just remember Analyst use R and our Mindset is different from base programmers.

:)
:)

**Comment by vikram-rawat** [comment]
I tried to run your example in a fresh folder and when I run the .exe this is what I get.

![image](https://user-images.githubusercontent.com/22342596/31114278-dff473be-a83a-11e7-85bf-61ba1185e976.png)

**Comment by zhengle-advantaseeds** [comment]
I experienced the same error as your 1st comment: when I install the same program into the same directory. I would uninstall all the version of that app, and reinstall it.

**Comment by Dripdrop12** [comment]
@vikram-rawat it looks like RInno did not find your installation of R (that's why the path starts with "none"). Are you using Microsoft R Open by chance?

**Comment by vikram-rawat** [comment]
Yes and I have r portable installed too.

**Comment by Dripdrop12** [comment]
That's probably why. RInno has not been tested with Microsoft R Open, and they probably messed with the software registry so RInno can't find it
