### ISSUE TITLE
does it uses Rportable or Normal R

### ISSUE THREAD

**Issue by vikram-rawat** [ficonsulting/RInno#27]
When I use the parameter include_r = TRUE

Does it installs the Rportable or NormalCRAN R or MRANR. Which R does it use and does it impact the authentication of the user.

Please I want to know it. Because if Authentication doesn't matter I would Always want to use MRAN R which is faster else I would normally use Rportable.

**Comment by zhengle-advantaseeds** [comment]
I think the program download the full version R from CRAN.

**Comment by Dripdrop12** [comment]
Yep, @zhengle-advantaseeds is correct. It uses a full version of R, but it uses a registry check to make sure you don't have it installed before doing so.

**Comment by Dripdrop12** [comment]
The MRAN version of R would be an interesting option. I'll look into providing an option to use MRAN R w/ intel MLK in a future release!
