### ISSUE TITLE
include_R Hangs the Process

### ISSUE THREAD

**Issue by vikram-rawat** [ficonsulting/RInno#30]
I am not sure if that is with low network in India but when It downloads R. it hangs for so long that i have to cut the process. I can download R within 2 minutes. But include_R command takes like forever.

Then at last I put the downloaded version of R in the app directory and it worked just fine. But it shouldn't take that long. it just doesn't download it after a few seconds. and hangs.

**Comment by Dripdrop12** [comment]
Vikram,

RInno is using `curl::curl_download` to download R. I'm not sure why it would be slower than a regular download, but I'll look into it for you. Thanks for the update!

**Comment by Dripdrop12** [comment]
I just bench-marked `curl_download` (the method used by RInno) against the base R `download.file` and their average time is within one second of each other. I imagine this is an internet connectivity issue that you may need to work around with a manual download.

Here is what I ran to test the issue on my end:
```
base_url <- "https://cran.r-project.org/bin/windows/base/R-3.4.2-win.exe"
filename <- "C:/Users/jhill/Documents/GitHub/RInno/R-3.4.2-win.exe"

microbenchmark(
    download.file(base_url, filename), 
    curl_download(base_url, filename))
```
```
Unit: seconds
                              expr      min       lq     mean   median       uq      max neval
 download.file(base_url, filename) 35.56914 36.58074 39.13694 37.31082 39.08186 155.6127   100
 curl_download(base_url, filename) 35.78271 37.34468 40.29466 38.71099 40.59981 121.1768   100
```
It's taking me about 40 seconds to download R regardless of the method.
