### ISSUE TITLE
specify location to install R

### ISSUE THREAD

**Issue by renejuan** [ficonsulting/RInno#31]
When using the option `include_R = TRUE`; R is installed using `/SILENT`. This works pretty good but of the options provided (https://cran.r-project.org/bin/windows/base/rw-FAQ.html#Can-I-customize-the-installation_003f) I think `/DIR` is very important. In enterprise environment the location where R is installed can have devastating effects (admin privileges; mydocs drive that is not available when working locally, etc.). Adding the `\DIR` option is a must in my opinion. This is a great package by the way!

**Comment by Dripdrop12** [comment]
Rene,

I absolutely agree. Next release will default to `\DIR` and provide an option for `/SILENT`. Does that sound good?

**Comment by renejuan** [comment]
I think it will be a good addition. Thanks again!

**Comment by Dripdrop12** [comment]
Rene,

Did you use an empty `/DIR` and leave it up to the user or install it in a specific location? If it requires an installation path, I may leave the default as `/SILENT` but allow developers to specify a directory that will work for their installation.  What do you think?

**Comment by renejuan** [comment]
Not sure I follow. If you include a `/DIR`; R installer does not seem to ask the user for a destination when the `/SILENT` option is also used. I tried `R-3.3.3-win.exe /SILENT /DIR` and R was installed under "My Documents". I think if a person specify a parameter such as `R_dir` in the `create_app()` then use `/DIR` if not then simply ignore it. Hope that helps.

**Comment by Dripdrop12** [comment]
That is exactly what I was wondering. The R tags interact and we can also use Inno Setup [constants](http://www.jrsoftware.org/ishelp/index.php?topic=consts) to make sure the path will work on other computers (i.e. `/SILENT /DIR=""{userdocs}""` instead of `/SILENT /DIR=""C:\\path\\to\\my\\docs""`). I wrote an example in `?run` . 

Feel free to send a pull request if we are speaking past each other.
