### ISSUE TITLE
error, R executable not found: none\bin\R.script.exe

### ISSUE THREAD

**Issue by hcji** [ficonsulting/RInno#38]
I compile my app follow the readme, but when I run the exe, it turns out an error: 
> error, R executable not found: none\bin\R.script.exe

I already add the path of R\bin and R64\bin to system path, but it is useless

**Comment by hcji** [comment]
When I uninstall the R and install my app and R, the error is fixed. I cannot demand my users do so, right ?

**Comment by Dripdrop12** [comment]
When you ran your original test, which version of R were you running? The registry query should only return "none" if you do not have a standard CRAN installation of R.

**Comment by hcji** [comment]
Oh,that reminds me. My R version 3.4.2 when I running the original test, but I forget change the version number when compiling. Thus, the version included should be 3.4.3 ? Is this the reason ?

**Comment by Dripdrop12** [comment]
I have heard that the MRAN version of R can cause similar issues, but those CRAN versions should work. Can you let me know what your R registry entry looks like when the error occurs?

**Comment by hcji** [comment]
To reappear the error in the original test, I uninstall the R and install origanl R version. Then I repeat the steps, well, it works fine this time. I dont know why. But it is fine, anyway. I will close this issue. Thank you.

**Comment by Dripdrop12** [comment]
Thanks @hcji. Please let me know if you have this error again. Because you are right, we do not want to force users to re-install R. That would be incredibly annoying.

**Comment by hcji** [comment]
This is the error information
![3g9z 3g rfftkfi2irf eo0](https://user-images.githubusercontent.com/17610691/34354820-ee992b44-ea6b-11e7-8d57-181221032712.png)

**Comment by hcji** [comment]
Then, I have to unstall R and install the software accompanied with R so that to fix this.

**Comment by Dripdrop12** [comment]
Can you provide the output from `Sys.info()` and a translation of that error message? Thanks!

**Comment by hcji** [comment]
I can't understand how to do that. but when I follow the help document with in the vignettes and get app from github, rather than replace the ui.R and server.R of the minimal example, this does not happen any more. Thank you very much.

**Comment by timat35** [comment]
Hi,  I have the same issue on a coworker computer. (but it does work on mine)
windows script host: 
Error: R executable not found:
none\bin\Rscript.exe

I've check and:
_ He has R 3.4.3, 32 bit and 64 bit install (C:\Program Files\R\R-3.4.3\bin\)
 and the key registry are present.

I compiled my app using R 3.4.2.

**Comment by timat35** [comment]
It does work, if I compile the app using R.3.4.3..
Does it mean the app must be compiled with the same version of R?
