### ISSUE TITLE
Warning message when running create_app() 

### ISSUE THREAD

**Issue by Aeilert** [ficonsulting/RInno#43]
I get the following warning message when running create_app() from the minimal example. 

```
create_app(app_name = "Your appname", app_dir = "app")
Warning message:
In data.row.names(row.names, rowsi, i) :
  some row.names duplicated: 270,276,279,288 --> row.names NOT used
```
RInno: 0.2.0
R: 3.4.3 
RStudio:  1.0.143 
OS: Windows 7

**Comment by Dripdrop12** [comment]
What do you get when you run?

```
utils::installed.packages()[c(270,276,279,288), 1]
```

**Comment by Aeilert** [comment]
I get: 
`> utils::installed.packages()[c(270,276,279,288), 1]`
` foreign       MASS       mgcv   survival` 
 ` "foreign"     "MASS"     "mgcv" "survival" `

**Comment by sollano** [comment]
I'm getting the same error message 10, R version 3.4.3.
