### ISSUE TITLE
Startup failed with error(s):  missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by georgemirandajr** [ficonsulting/RInno#45]
I was able to use the example app to install on my Desktop (my organization doesn't allow anything installed on Program Files or even My Documents). But when I double-click the shortcut to the desktop app I get a startup error about missing value where TRUE/FALSE needed.
Below is the error log from the example app. Any idea what is happening here? I'm running Windows 7 on 64-bit machine. I used the include_R=TRUE and include_R=FALSE and neither one made a difference.

library paths:
... C:/Users/e525902/Desktop/Your appname/library
... C:/R/R-3.4.0/library
working path:
... C:/Users/e525902/Desktop/Your appname
Loading required package: methods
Warning message:
package 'jsonlite' was built under R version 3.4.3 
Warning message:
package 'devtools' was built under R version 3.4.3 
Warning message:
package 'httr' was built under R version 3.4.3 
ensuring packages: jsonlite, shiny, magrittr

Pinging www.google.com [172.217.5.196] with 32 bytes of data:
Reply from 172.217.5.196: bytes=32 time=5ms TTL=46

Ping statistics for 172.217.5.196:
    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 5ms, Maximum = 5ms, Average = 5ms
Startup failed with error(s):

missing value where TRUE/FALSE needed

**Comment by georgemirandajr** [comment]
The issue was resolved by installing 'httpuv'. For some reason that package failed to install when I initally set up the project. After that was installed correctly, I deleted the example app and ran the code `again.

`example_app(wd = getwd())
create_app(
    app_name = "myapp", 
    app_dir = "app", include_R = TRUE,
    pkgs = c("shiny", "jsonlite", "httr")
)
compile_iss()`

**Comment by Dripdrop12** [comment]
Thanks for reporting this! Please let us know if you experience any other bugs.
