### ISSUE TITLE
Package not found error

### ISSUE THREAD

**Issue by sollano** [ficonsulting/RInno#47]
Hey Jon, hope you're doing alright.

So, I updated RInno and re-builded the executable for my app, and ran into a issue. It installs fine, but when it tries to update the packages, it tries to update a package called ">=1.0.5", followed by the error 'package ">=1.0.5" not found'. 

I looked back at the old installed version, and noticed that were differences in the utils/config.cfg.

The old version just listed the package names that I set to install separated by commas in the "pkgs" function , while the newer version was like this:

```r

  "appname": "AppInventarioNativas",
  "pkgs": {
    "pkgs": {
      "shiny": ">=1.0.5",
      "DT": ">=0.2",
      "formattable": ">=0.2.0.1",
      "readxl": ">=1.0.0",
      "plyr": ">=1.8.4",
      "tidyr": ">=0.7.2",
      "dplyr": ">=0.7.4",
      "ggplot2": ">=2.2.1.9000",
      "lazyeval": ">=0.2.0",
      "ggdendro": ">=0.1.20",
      "ggthemes": ">=3.4.0",
      "xlsx": ">=0.5.7",
      "httr": ">=1.3.1"
    },

```

So I imagine the problem lies over there. Do you know how I can solve this? This is the code I am using to build the .exe:

```r

create_app(
  app_name     = "AppInventarioNativas",
  app_dir      = "RInno_files",
  app_repo_url = "https://github.com/sollano/AppInventarioNativas",
  pkgs         = c("shiny", "DT", "formattable", "readxl", "plyr", "tidyr","dplyr", "ggplot2", "lazyeval", "ggdendro","ggthemes","xlsx"),
  app_icon     = "LAB_logo.ico",
  setup_icon   = "LAB_logo.ico",
  publisher    = "treelab ufvjm",
  pub_url      = "http://gorgens.wixsite.com/treelab",
  dir_out      = "exe_folder",
  info_before  = "info_before.txt",
 info_after    = "info_after.txt",
 auth_token   =******

)
compile_iss()


```

Also, something I tried a while back and noticed is that since this app checks for version updates on my github page, the .exe will not launch without a internet connection. I wasn't sure if I should open a issue for this or not, and this was the reason I rebuild the .exe, to see if it would work offline now. So if you think it is worth it, I'll open another issue and we can take a look at.

Thanks again for this package, cheers!

RInno: 0.2.0
R: 3.4.3
OS: Windows 10

**Comment by Dripdrop12** [comment]
I'm sorry you're having difficulty with this Sollano. Can you share some of your `ensure.R` file? That ">=1.0.5" error is thrown by the `ensure` function. It looks like your app may have an old copy of the file that does not handle the version check properly. This release, v0.2.0, added functionality to use conditional statements for software dependency requirements.

For the internet connectivity piece, we had some users who could not use ping because of company security policies. We've added `!httr::http_error("www.google.com")` in a few places to check for an internet connection and handle it more smoothly. It might be worth starting a new issue to discuss that a bit more and give people a chance to chime in on different use cases.

**Comment by sollano** [comment]
Thanks jon. Here is the ensure function from the ensure.R file:

```r

ensure <- function(pkg, repo = config$pkgs$cran, load = TRUE) {
  setWinProgressBar(pb,
    value = grep(paste0("\\b", pkg, "\\b"), pkgs) / (length(pkgs) + 1),
    label = sprintf("Loading - %s...", pkg))

  if (!(pkg %in% row.names(installed.packages()))) {
    install.packages(pkg, repo = repo, lib = applibpath)
  }
  if (load) {
    library(pkg, character.only = TRUE)
  }
}

About the internet connection problem, if it still persists after we solve this, I'll be sure to make an issue, then. Thanks!

```

**Comment by Dripdrop12** [comment]
Here is the newest version of ensure: https://github.com/ficonsulting/RInno/blob/master/inst/installation/ensure.R

Do you have a guess as to how the old one is still being used?

**Comment by sollano** [comment]
No idea. I updated the package in two different computers, and got the same error. I'll delete the package on my R folder and try again. But I am running the 2.0 version of the package. This really is strange, it should have updated the function. I'll try it and report to you.

**Comment by sollano** [comment]
Alright Jon, got it. I was watching the utils folder closely while running the `create_app`  function, and found the issue. When I run this function, the files inside the utils folder are not overwriting the existing files inside of it, other than the config.fcg. So the ensure.R file, as well as package_manager.R and get_app_from_app_url.R files are left unmodified, and outdated.

When I manually deleted the files and ran `create_app` again, the files were created, now with the updates. So this function is having trouble overwriting existing files inside this folder.

**Comment by Dripdrop12** [comment]
Do you think anyone is customizing those files? Or would it be okay to over write them to make sure updates flow through existing apps?

**Comment by sollano** [comment]
I don't think so. Since they are created when you the function from your package, I personally never touched them when the app was running ok. I don't see why they would. I think they should be overwritten like you said, the ensure that updates flow through.

**Comment by sollano** [comment]
Jon, sorry to keep bothering you with this but, now the .exe checks and installs all packages, but when it tries to open the shiny app on chrome, a strange windows opens, and nothing else happens. This was not happening with the previous build, so it has something to do with this new .exe.  Here's a screen shot:
![print_rinno](https://user-images.githubusercontent.com/19754326/35698588-adaea6c4-0774-11e8-8e2c-656d4d953ff0.jpg)

This is actually chrome, because if chrome is open prior to running this, this opens up as a separate window, with the app grayed out. So it is finding chrome and launching it, but for some reason it's not working properly. I tried re-installing chrome, but it didn't help. Do you have any idea to what may be causing this?

**Comment by chasemc** [comment]
This is only a guess, but it might be related to the app now opening chrome in app mode : 9aed2a2


You could try, locally, rolling back changes to:   RInno/inst/installation/app.R

Specifically:
```r
if (user_browser == "chrome") {
    if (chrome != "none") {
      chrome <- gsub("\\\\", "/", file.path(chrome, "chrome.exe", fsep = "\\"))
      options(browser = chrome)
      # Launch Chrome in app-mode
      launch_browser <- function(appUrl) {
        message('Browser path: ', chrome)
        system(sprintf('"%s" --app=%s', chrome, appUrl))
      }
    }
```

**Comment by Dripdrop12** [comment]
@sollano If you are still having an issue with Chrome running in app mode, feel free to open another issue. I just closed this one because the first piece has been resolved. There is now an option in `create_app` called `overwrite` which defaults to `TRUE`.

**Comment by sollano** [comment]
@Dripdrop12 Alright, thanks for resolving the first issue, though. I think I'll open up another one, since chrome is still crashing for me. Maybe I'll do a little more testing first, but I'll be back to it later. Thanks!

**Comment by turqoisehat** [comment]
Has anyone ever actually gotten Rinno to work? Not to be insulting here, but I'm legitimately curious.

**Comment by sollano** [comment]
@turqoisehat Rinno was working fine for me until one of the recent updates changed a few things, and broke it for me. But before that it worked fine.

**Comment by Dripdrop12** [comment]
@turqoisehat - many people have benefited from it and we have closed 70+ issues. If you have a simple reprex, please submit it as an issue and I'd be happy to work through it with you.

@sollano - I'm sorry to hear it is not working for you right now. Let me know if there is anything I can do to help. We have been transitioning to a more self-contained deployment package w/ stand-alone UI and binaries of all dependencies. Sorry if this is causing an issue for you. Feel free to also submit a ReprEx. I'm all ears.
