### ISSUE TITLE
Rscript exe Path

### ISSUE THREAD

**Issue by willbradley** [ficonsulting/RInno#5]
The R executable is not found when launching a newly installed app if R is not located in C:/Program Files/.

**Comment by Dripdrop12** [comment]
Yeah, the first pass was to work with R installed in a traditional location. We'll have to add support for R being located in `My Documents` or elsewhere, especially for organizations with IT controls that redirect R away from `C:/Program Files`

**Comment by Dripdrop12** [comment]
@willbradley,

This most recent patch should address your issue with the executable's path. I updated the methodology to pull the path off of each computer's registry, so it should be much more robust to these types of situations.

I did the same thing for the supported browsers (chrome, firefox and ie).

Best,
Jon

**Comment by sollano** [comment]
Hi,

 I'm having this issue too, even with the dev version of the app. But I checked and R is installed under C:\Program Files. Maybe the issue is that my computer is running windows in Portuguese-br. Anyway, the error shows R executable not found: none\bin\Rscript.exe.

Can you help out? Thanks!

**Comment by Dripdrop12** [comment]
It looks like RInno was not able to find R. "none" is returned by the registry query if it does not find a copy of R installed on the computer.

Can you share more of your code with your create_app call?

**Comment by sollano** [comment]
> It looks like RInno was not able to find R. "none" is returned by the registry query if it does not find a copy of R installed on the computer. Can you share more of your code with your create_app call?

Oh, I see. Yes, of course. the create_app call I'm using is:
```R
create_app(app_name = "nativas_app",
      
  pkgs =c("DT", "formattable","readxl", "plyr","tibble","tidyr","dplyr","lazyeval","ggplot2","scales","ggdendro","ggdendro","xlsx","rJava","xlsxjars") )

compile_iss()

```

**Comment by Dripdrop12** [comment]
Thanks. Try adding `include_R = TRUE` to your create_app call. That should work, but can you also dig into the log directory of "nativas_app" post-installation? It should have some more information about the root cause of your issue.

**Comment by sollano** [comment]
> Thanks. Try adding include_R = TRUE to your create_app call. That should work, but can you also dig into the log directory of "nativas_app" post-installation? It should have some more information about the root cause of your issue.

Adding that argument makes the installer ask to install R, but installing (re-installing) does not help. It shows the same error as before. The log folder is empty... I'm trying to find out how the function tries to find the R folder, but with no success.

**Comment by sollano** [comment]
So, I edited the regpaths.json from the utils folder, and changed the path of R from "none" to "C:\\Program Files\\R\\R-3.4.1\\bin\\Rscript.exe", But still it says R executable not found (even though it is located in that path).

**Comment by Dripdrop12** [comment]
Try "C:\\Program Files\\R\\R-3.4.1\\bin\\Rscript.exe"

**Comment by Dripdrop12** [comment]
That error message is produced by run.js, which is a JScript file that starts R.

**Comment by Dripdrop12** [comment]
run.js starts the package management process (package_manager.R), which then starts the app with (app.R)

**Comment by Dripdrop12** [comment]
code.iss is where the registry query is stored. We try to find either the HKEY_CURRENT_USER or the HKEY_LOCAL_MACHINE entry, and derive the installation path from there.

Can you take a look at the R docs on [registry entries](https://cran.cnr.berkeley.edu/bin/windows/base/rw-FAQ.html#Does-R-use-the-Registry_003f) and let me know which entry your machine has?

**Comment by sollano** [comment]
> Can you take a look at the R docs on registry entries and let me know which entry your machine has?

So, I have solved this issue. The problem was that since my computer is x64, I install only the x64 version of R. It seems that some of the software you use is x86. Once I installed the x86 version of R, the app ran fine, and opened on chrome.

But anyway, here's the registry
![reg](https://user-images.githubusercontent.com/19754326/29898103-655d5002-8dba-11e7-8969-c4c06a240ece.jpg)

Now I'm having another error, but I I'll do some more tests here before making another issue.

Thank you very much for the attention!

**Comment by sollano** [comment]
> Now I'm having another error, but I I'll do some more tests here before making another issue.

Ok, so the other problem I was having was with chrome. The app would crash on startup unless chrome was already opened. But this was fixed reinstalling chrome. The app is running fine now.

Thanks again for this great package, John!

**Comment by Dripdrop12** [comment]
Great! Thanks for taking a look at it :)

**Comment by chasemc** [comment]
I have a dependency on an command line tool executable .exe that is called from shiny.  RInno transfers everything really nicely... except any .exe files. Any thoughts on a quick fix?
