### ISSUE TITLE
Runtime Internal Error: Cannot read an encrypted file before the key has been set.

### ISSUE THREAD

**Issue by vonplato** [ficonsulting/RInno#55]
Hello,

I have followed instructions about placing ISCrypt.dll into my RInno folder [I found it was already there but I copied over it with the file from your link] and have set a password and encryption to YES when I create iss(). 

However, when I run the installer afterwards I get this error. 

Runtime Error
Internal Error: Cannot read an encrypted file before the key has been set.
https://i.imgur.com/Jw3GNLu.png

Followed by this error:
Runetim Error
Could not call proc.
https://i.imgur.com/NfqghEL.png

Googling this error has failed me in terms of finding a solution.

If I do not set a password / encrypt then the installer does function. Any ideas are places to start to evade this error?

This is on Win 8.1 with R 3.4.3 and Rstudio. All packages are up to date. Let me know if you need more information.

**Comment by Dripdrop12** [comment]
Can you share your `create_app` call? I have not gotten this error before, but maybe I can replicate it with your code ;)

**Comment by AshutoshAgrahari** [comment]
Hello,

I am also getting the same issue while creating encrypted RInno installer by following the notes from https://ficonsulting.github.io/RInno. 

### create_app function is working.
create_app(app_name = "app", 
           app_dir = "app",
           include_R = T,
           R_version = "3.4.1", 
           inst_pw = "0r4nGE5",
           dir_out = "app_installer"
           )

### Able to compile the code also to generate installer.
compile_iss()

### Installer not working.
but while installing through the installer, get an error message.
![image](https://user-images.githubusercontent.com/22572910/41272035-35981e12-6e31-11e8-9e0f-e8c2455e8165.png)
![image](https://user-images.githubusercontent.com/22572910/41272047-44baa4a0-6e31-11e8-991e-ad97afb8221e.png)

Please let me know how to fix this issue.

**Comment by Dripdrop12** [comment]
It looks like the LICENSE was causing this error. Inno Setup would try to open it before decrypting the file, so I added a tag to not encrypt it. Let me know if that fixes it for you!

**Comment by AshutoshAgrahari** [comment]
Thanks for the fix in quickest possible time, Jonathan
It's working. Now I am able to install app with a password.
