### ISSUE TITLE
Timeout Error - Firewall issue

### ISSUE THREAD

**Issue by TheGladiator2017** [ficonsulting/RInno#56]
Hi Jonathan!  I was running your example and I got the following error when I ran the setup_myapp.exe file. I get a pop up saying that "Ensuring package dependencies" (with a progress bar) and the a fail popup saying "Startup failed with error(s): Timeout was reached: Connection timed out after 1000 ms". I am sure it has to do with the firewall settings of my organization, is there anything that can be done on my end?

**Comment by Dripdrop12** [comment]
Hadley's response here might help https://github.com/r-lib/devtools/issues/877.
