### ISSUE TITLE
App will only run when chrome is running in the background

### ISSUE THREAD

**Issue by TheGladiator2017** [ficonsulting/RInno#57]
Hi!
I have noticed that the application that I created will only run if and only if I have chrome opened in the background. Otherwise, I will get Listening on http://127.0.0.1:1984 and it stuck there forever.

I updated my chrome browser and everything but it is still the same issue. Any ideas on how to fix that?

**Comment by Dripdrop12** [comment]
Did you add this code snippet to your server.R file?

https://github.com/ficonsulting/RInno#serverr-requirements

**Comment by chasemc** [comment]
I am encountering the same issue.  It doesn't seem to matter if that snippet is included or not.

**Comment by chasemc** [comment]
Temporary fix is to prevent opening chrome in app mode:
In "utils/app.R", replace:
```R
      shiny::runApp(app_path, launch.browser = launch_browser, port = 1984)
```
With:

```R
      shiny::runApp(app_path, launch.browser = TRUE)
```

**Comment by Dripdrop12** [comment]
This is a strange issue. I've got apps installed on Windows 7 (64-bit) and a new Windows 10 (64-bit) machine, and I'm not able to replicate the behavior :(

**Comment by Dripdrop12** [comment]
@chasemc Do you think we should add an option to turn app mode off?

**Comment by chasemc** [comment]
Since it seems irreproducible at the moment that might be a good idea.  It's fine if you have close contact with your users, but when building for a wide audience this might cause some issues.

**Comment by Tebatu** [comment]
Hi, 
I found this thread dealing with a similar error: https://github.com/rstudio/shiny/issues/681
Could adding `&` in `launch.browser` help with the issue?

**Comment by chasemc** [comment]
@Dripdrop12

RE: https://github.com/rstudio/shiny/issues/681#issuecomment-393903013  


From: http://stackoverflow.com/questions/27609651/chrome-browser-does-not-display-page-unless-already-open-in-shiny?noredirect=1#comment43641763_27609651

`</body></html>" &', browser.path, appUrl))`

```r
launch.browser = function(appUrl, browser.path='/usr/bin/chromium-browser') {
  system(sprintf('"%s" --disable-gpu --app="data:text/html,<html>
<head>
<title>Configuration</title>
</head>
<body>
<script>window.resizeTo(800,500);window.location=\'%s\';</script>
</body></html>"', browser.path, appUrl))
}
```
```r
launch.browser = function(appUrl, browser.path=path) {
  system(sprintf('"%s" --disable-gpu --app="data:text/html,<html>
    <head>
    <title>System Configuration</title>
    </head>
    <body>
    <script>window.resizeTo(830,675);window.location=\'%s\';</script>
    </body></html>" &', browser.path, appUrl))
}
```

**Comment by Dripdrop12** [comment]
I'm going to roll-back app mode and focus on a true stand-alone feature instead of relying on Chrome (they stopped supporting the `--app` tag so it is only a matter of time before that starts breaking permanently)
