### ISSUE TITLE
app.R did not return a shiny.appobj object

### ISSUE THREAD

**Issue by MFA-bmayer** [ficonsulting/RInno#61]
First, let me say I'm very grateful for this package! Deploying apps locally is a great option when shinyapps.io or a local shiny server aren't possible.

I've had two users download the app via the installer and both have the following error when launching the application:
app.R did not return a shiny.appobj object.

I would greatly appreciate any help!

**Comment by Dripdrop12** [comment]
Thanks! Was this only a few users or is it everyone? Can you share more details about the app and your `create_app` call?

This error can be thrown if `app_dir` does not contain a shiny app (app.R or ui.R/server.R). So first, make sure that `create_app(app_dir = "directory with a shiny app or flexdashboard")` has all the files it needs.

**Comment by MFA-bmayer** [comment]
Here is the `create_app()` call:
`create_app(
  app_name    = "Geographic Survey Analyzer", 
  app_dir     = "confirmed app directory" ,
  dir_out     = "wizard",
  pkgs        = c("shiny", "shinythemes","htmlwidgets", "DT", "shinydashboard", "shinyWidgets",
                  "stringr", "RODBC", "RODBCext", "leaflet", "geojsonio", "rgdal", "raster", "sp",
                  "rpivotTable", "rvest", "plyr", "dplyr", "knitr", "rmarkdown", "withr", "devtools"),  # CRAN-like repo packages
  include_R   = TRUE,     
  include_Pandoc = TRUE,
  R_version   = "3.4.3",  
  default_dir = "pf", 
  app_version = "1.0.1",
  setup_icon = "if_settings.ico",
  app_icon = "if_Geo_2745002.ico"
)     

compile_iss()`

In terms of the application, what details do you need?

**Comment by Dripdrop12** [comment]
Is it a single-page app using app.R? Or are you using global.R, ui.R and server.R?

RInno's startup sequence calls the equivalent of `shiny::runApp(app_dir)` [here](https://github.com/ficonsulting/RInno/blob/master/inst/installation/app.R) as the last step. You can trouble shoot this by running something similar to make sure it will work in the compiled .exe

**Comment by MFA-bmayer** [comment]
It is a single-page app, app.R.

I ran the `shiny::runApp(app_dir)` and the app launches successfully on my machine.

**Comment by Dripdrop12** [comment]
Good. Some other users have had issues with single-page apps and they were able to resolve the issue by breaking them out. I have not been able to replicate the errors though. Single-page apps have always worked for me.

Here are a few more questions:

Is there an app.R file in the resultant installation directory? "C:\Program Files\Geographic Survey Analyzer\app.R"

Does the file have something like `shinyApp(ui = ui, server = server)` in it?

**Comment by MFA-bmayer** [comment]
Thanks! I will definitely break apart the app.R into ui.R and server.R and see if there are different results.

The resultant installation directory has the app.R and the file itself includes `shinyApp(ui = ui, server = server)`. 

Would `if ( interactive() ) {}` have any impact here?

**Comment by Dripdrop12** [comment]
Yes! R is started in non-interactive mode using rscript.exe.

**Comment by Dripdrop12** [comment]
Here is another potential answer that I came up with a few months back:

https://stackoverflow.com/questions/45698475/running-r-shiny-through-rinno-package

You can try to remove `shinyApp(ui = ui, server = server)` from your app.R file and see if that helps!

**Comment by MFA-bmayer** [comment]
It seems that removing `if ( interactive() ) {}` was the key! It works fine now. Thanks for the assistance!
