### ISSUE TITLE
Removing exe from installer?

### ISSUE THREAD

**Issue by chasemc** [ficonsulting/RInno#62]
I was wondering why you decided to remove exe files from being able to be installed? (I was wondering why I was having to add them to .iss manually)

https://github.com/ficonsulting/RInno/blob/f9f29c87387c0b890f38b6c00208bec0b54b1206/R/files_section.R#L21

**Comment by Dripdrop12** [comment]
I was trying to make sure that previously compiled installers don't get included in future compilations. You're right. We should be more specific here, and possibly drop the msi extension.

**Comment by Dripdrop12** [comment]
There has always been an option to include a `file_list`, which will override the default behavior:
```
create_app(
   app_name = "myapp",
   app_dir = "app",
   file_list = "path/to/my/exe"
)
```
My intention in removing .iss etc was to make sure the pre-compile artifacts don't get passed on to the user's computer. For example, after running `compile_iss`, we don't want to include the installer within itself.

**Comment by Dripdrop12** [comment]
I'd rather not explicitly list all the .exe files that are included with the installer @chasemc. Can you use the file_list to make sure yours don't get removed?

We're probably going to include more software in the future and I'd rather not have to maintain this explicit list. Developers can manage it on their end ;)
