### ISSUE TITLE
Issue with path to Rscript.exe

### ISSUE THREAD

**Issue by benoitrauturier** [ficonsulting/RInno#64]
Hi, 

First of all, thanks for this awesome package ! 

I have an issue that might be related to #5. When I launch the installer on a computer without any previous version of R , the installer does install the app and R, but when clicking on the app icons, I get an error message (none/bin/RScript.exe not found). 

My quick fix for now is to uninstall only the app and then reinstall it and in works just fine, but that is not very practical for my users. 

My call to create_app is : 
```
create_app(app_name = "My app",
           include_R = T,
           pkgs = c("shiny", "DT", "shinydashboard","tidyverse", "jsonlite", "stringr", "shinythemes", RPostgreSQL = "0.6-2"))
```
My sessionInfo() is : 
```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magrittr_1.5 RInno_0.2.0 

loaded via a namespace (and not attached):
[1] compiler_3.4.2 tools_3.4.2    yaml_2.1.18  
```

**Comment by trybik** [comment]
I confirm this bug

**Comment by trybik** [comment]
I believe this is now fixed in devel by 2ed9b308 , just not yet on CRAN

**Comment by benoitrauturier** [comment]
Thanks @trybik . I confirm that installing the development version solved that issue :).

**Comment by Dripdrop12** [comment]
https://github.com/ficonsulting/RInno/commit/2ed9b308dec9c9758df51ad4536872da27ec7b8d
