### ISSUE TITLE
include_Rtools

### ISSUE THREAD

**Issue by fdetsch** [ficonsulting/RInno#67]
Hi, 

thanks for the wonderful work you put into this project. I wonder, would it be possible to add an argument `include_Rtools` (similar to other `include_*` options) in function `create_app()`?  

In my current app, I am using the package [**openxlsx**](https://cran.r-project.org/web/packages/openxlsx/index.html) to create an Excel file (.xlsx) that contains both text and image data (ie. inserted .jpg files). Obviously, this output cannot be generated with simple `read.csv()` calls. In order to export the resulting workbook using `openxlsx::saveWorkbook()`, in turn, Rtools needs to be installed.

Of course, I could manually download and install Rtools on each and every machine deploying my app to get things going. However, I think that implementing an `include_Rtools` option would perfectly fit into the conceptional design of **RInno** to allow the user to set things up properly in just one go.

**Comment by chasemc** [comment]
For temporary fix see also: https://github.com/ficonsulting/RInno/issues/48#comment-363185039

**Comment by Dripdrop12** [comment]
This is in dev. Let me know if you want to make any changes or you find any bugs ;)

**Comment by fdetsch** [comment]
Works like a charm, thanks!
