### ISSUE TITLE
Startup failed with errors: Could not resolve host:www.google.com

### ISSUE THREAD

**Issue by nimasol** [ficonsulting/RInno#68]
After running _setup_myapp.exe_ to generate an executable app  I get an error: "Startup failed with errors: Could not resolve host:www.google.com"! I guessed it might be  an issue correlating to chrome!? Then I tried all suggestions [here ](https://github.com/ficonsulting/RInno/issues/57), however, I could not solve it. Any idea what could be the reason?
I posted this issue [here ](https://stackoverflow.com/questions/49534025/error-by-using-rinno-to-deploy-r-shiny-app-as-a-standalone-application?noredirect=1#comment86077246_49534025 )too however no answer up to now!

**Comment by xsswang** [comment]
I have the same problem. The app runs OK in a local machine. But when I installed the app onto a remote desktop, it reports the "could not resolve host" thing. Seems related to firewall or proxy, since the remote desktop has rigorous control over internet connection.

**Comment by Dripdrop12** [comment]
That would make sense. If the remote machine can't ping google, the app will fail. There is an internet connection check which allows the app to run without an internet connection after having connected at least once to download package dependencies. If the remote machine can't get the packages from the internet, you'll need to download and include them as `locals`.

See #34 for more info.
