### ISSUE TITLE
Non-compatibility with flexdashboard framework

### ISSUE THREAD

**Issue by HanjoStudy** [ficonsulting/RInno#7]
RInno framework assumes that Shiny App was developed using conventional ui.R and server.R setup. Should also accommodate flexdashboard markdown files in future.

In compiled folder utils/app.R, this would ensure that it can run the flexdashboard.Rmd format. Having issues with pandoc availability
```
if (config$app_repo[[1]] != "none") {
  app_path <- file.path(system.file(package = config$appname), "app")
  #shiny::runApp(app_path, launch.browser = T)
  rmarkdown::run(file = list.files(app_path, pattern = ".Rmd") ,dir = app_path, shiny_args =list(launch.browser = T))
  

} else {
 #shiny::runApp("./", launch.browser = T)
  rmarkdown::run(file = list.files("./", pattern = ".Rmd") ,dir = "./", shiny_args =list(launch.browser = T))
}
```

**Comment by Dripdrop12** [comment]
This is a great suggestion and thank you for providing the code! Would you like to submit this as a pull request? I would be happy to work with you on it @HanjoStudy

**Comment by HanjoStudy** [comment]
Hi @Dripdrop12, let me fork the project and play with it a bit to see if I can get it to accommodate Flexdashboards. Ill do a pull request once I have gone through all of it and started working on it

**Comment by Dripdrop12** [comment]
Thanks for putting that together Hanjo! You are officially a contributor to RInno :)
