### ISSUE TITLE
Bug in CRAN version comparison

### ISSUE THREAD

**Issue by trybik** [ficonsulting/RInno#70]
This is a minor one: when pkg has "-" as a third version number, the latest CRAN version comparison does not work with auto-generated version number from installed package. This is because "x.y-z" string is compared with "x.y.z" string in https://github.com/ficonsulting/RInno/blob/master/inst/installation/ensure.R#L29 ; for instance:

> pkgVersionCRAN("MASS") == "7.3.49"

An easy and consistent fix is e.g. to put `numeric_version( ... )` around https://github.com/ficonsulting/RInno/blob/master/inst/installation/ensure.R#L104 .

Best,
Mik

**Comment by Dripdrop12** [comment]
@trybik I think it about time you get listed as an official contributor ;) Wanna send this as a quick pull request?
