### ISSUE TITLE
Is it possible to make this work with RMarkdown runtime: shiny?

### ISSUE THREAD

**Issue by woodwards** [ficonsulting/RInno#77]
Is it possible to make this work with RMarkdown runtime: shiny?

I have an Rmd that produces an interactive document using shiny, leaflet, ggplot. Can i use RInno to share it with colleagues (non R users) without having to host it on shinyapps.io? (which works but we're not ready to pay for the subscription yet).

**Comment by Dripdrop12** [comment]
You should be able to convert it into a flexdashboard pretty easily. Afterwards, you should add `include_Pandoc = TRUE`, so that the package provides Pandoc for users that need it.

**Comment by Dripdrop12** [comment]
@HanjoStudy added this feature ;)

**Comment by woodwards** [comment]
Great! Where do I find it/how do I use it? Or does it take some time to come through as an update?

**Comment by Dripdrop12** [comment]
https://rmarkdown.rstudio.com/flexdashboard/ :)

**Comment by Dripdrop12** [comment]
RInno supports them like shiny apps, but they are similar to `rmarkdown`

**Comment by woodwards** [comment]
Oh I thought you meant that Hanjo had add Rmd support to RInno. 

Yes I have used flexdashboard before but not too keen to completely redesign my UI.
