### ISSUE TITLE
Is there a way to directly pass session.info in Rinno

### ISSUE THREAD

**Issue by vikram-rawat** [ficonsulting/RInno#79]
Yesterday I build the app that I needed SQLite for. It doesn't even work fine on my computer but when I tried it on the user computer it couldn't even download data.table at all. 

and after when I installed data.table manually it got stuck into this part I

![image](https://user-images.githubusercontent.com/22342596/39288472-c0f6922e-4945-11e8-8f61-b53382761b9b.png)

I have no idea why is happening

Apps works fine. You can even check that on https://vikramsinghrawat.shinyapps.io/HRDashboard/

```
require(RInno)

example_app(wd = getwd())

create_app(
    app_name = "Dashboard", 
    app_dir = "HRdashboard",
    pkgs = c("shiny", "jsonlite", "httr",'RPostgres',
             'readxl',
             'ggthemes',
             'plotly'
             ,'lubridate'
             ,'DBI'
             ,'pool'
             ,'data.table'
             ,'shiny'
             ,'shinyBS'
             ,'flexdashboard'
             ,'shinydashboard'
             ,'tidyverse'
             ,'shinyjs'
             ,'DT'
             ,'RSQLite'
             ,'DBI'),
    include_R   =TRUE,
    R_version   ="3.4.3"
)

compile_iss()

```

This is the code I ran to build the app. and Now everything I do it just gets stuck on this bar

![image](https://user-images.githubusercontent.com/22342596/39288596-3c9ec8ba-4946-11e8-9a0e-dc987f3a300e.png)

what should I do now.

**Comment by vikram-rawat** [comment]
I am really very sorry to bug you for this.

I found the problem I was using a few same packages twice in the name. 

But now it runs fine on my computer but I run it on somebody else's computer I have to load a few packages manually.

like DT and data.table

is there any shortcut to that too...

**Comment by vikram-rawat** [comment]
![asdfasdf](https://user-images.githubusercontent.com/22342596/39302254-9fb553b4-496f-11e8-9eec-3f87512b6c65.png)
![asdfa](https://user-images.githubusercontent.com/22342596/39302281-b6175544-496f-11e8-9d0f-eb0bb702ca1f.png)
![asdfaaa](https://user-images.githubusercontent.com/22342596/39302286-bbc81ae6-496f-11e8-8dd2-cfbe2ea9426b.png)

**Comment by Dripdrop12** [comment]
It looks like you are using a development version of the DT package from Github. It is only at version 0.4 on CRAN. To continue using that version of DT, you can move it to the `remotes` section of your `create_app` call for now.

This is related to #53, so I'm linking them up and closing this issue out. Let us know if you have any other issues!

**Comment by vikram-rawat** [comment]
Thanks for the reply. I didn't even realize that thanks for pointing it out to me.
