### ISSUE TITLE
App doesn't work offline

### ISSUE THREAD

**Issue by vikram-rawat** [ficonsulting/RInno#80]
I have an app that is connected to a local SQLite file. It just displays a dashboard and it works when I am Online.

But I have no idea why it doesn't work when I am offline.

**Comment by Dripdrop12** [comment]
What are some of the errors you get in your app's `log/error.log`?

**Comment by Dripdrop12** [comment]
Is this similar to #57?

**Comment by vikram-rawat** [comment]
I don't think so in my case chrome was open when I ran it. Just to be
double sure I will try that and let you know about it.

रवि, 3 जून 2018, 8:23 am को Jonathan Hill <notifications@github.com> ने
लिखा:

**Comment by Dripdrop12** [comment]
check out the dev branch. I'm working on a pretty significant change that will remove the need for an internet connection (except for continuous installation app frameworks).
