### ISSUE TITLE
Issue with opening app created with RInno

### ISSUE THREAD

**Issue by joe4go** [ficonsulting/RInno#81]
Hi,

I'm getting an error saying that the shiny package is unavailable when I try and run an app that I've compiled with RInno.

Here is the app that I'm trying to compile: [app.txt](https://github.com/ficonsulting/RInno/files/2005930/app.txt)

when I create the app I'm sure to put shiny in:

create_app(app_name = "shinyapp", app_dir = paste(output.dir,"shinyapp",sep=""), pkgs = c("jsonlite", "shiny", "httr"))

compile_iss()

But this is the error that I'm getting when I have installed the program and then go to open it:

![image](https://user-images.githubusercontent.com/39310880/40071453-b9e06ece-5868-11e8-9314-2865f9a851a8.png)

Any help would be greatly appreciated.

**Comment by Dripdrop12** [comment]
Try deleting all the `require`/`library` statements at the top of your app, and changing your `create_app` call to:

```
create_app(
  app_name = "shinyapp",
  app_dir = "appdir",
  pkgs = c("jsonlite", "shiny", "httr", "htmlwidgets", "crosstalk"),
  remotes = "ThomasSiegmund/D3TableFilter" # this package is not available on CRAN
)
```

Also, you need to replace the last line of the app `
runApp(list(ui=ui,server=server))` with `shinyApp(ui = ui, server = server)`.

That got it running for me ;)
