### ISSUE TITLE
Error connecting to chrome port 80 while starting the application 

### ISSUE THREAD

**Issue by jackliu333** [ficonsulting/RInno#82]
I'm having issue starting up the app using the example code. The error message looks like below.

![image](https://user-images.githubusercontent.com/18097461/40229330-7a612684-5ac6-11e8-8ed9-03417adb113a.png)

Is it because of network setting? I'm testing it within company's network, although I can successfully launch it when trying it out at home.

**Comment by jackliu333** [comment]
Btw, after changing to IE the error becomes like this:
after change: "user_browser": "ie"
![image](https://user-images.githubusercontent.com/18097461/40229532-15e6c802-5ac7-11e8-84b5-c60eb8e02636.png)

**Comment by jackliu333** [comment]
Is there a way to set proxy while starting up the application?

**Comment by Dripdrop12** [comment]
Not out of the box in RInno, but I'm sure there is a way to make shiny launch using a proxy. Need to do more research here.

**Comment by Dripdrop12** [comment]
Check out the develop branch of RInno, we have made a fundamental change in the way packages are delivered which should resolve this issue. An internet connection will only be required for apps designed to run using a continuous installation framework.
