### ISSUE TITLE
Something Wrong With DT package

### ISSUE THREAD

**Issue by vikram-rawat** [ficonsulting/RInno#83]
I wrote a shiny app which has some DT in it but when I convert it to Rinno. It behaves a little odd. Just to make sure there is nothing wrong with the version of the package I reinstalled the DT package just to make sure that the package I am using in shiny and the package that the Rinno uses are both the same.

You can see that there are slight differences in the implementation of DT.

![image](https://user-images.githubusercontent.com/22342596/40734197-5a1193ee-6455-11e8-8a4c-3fc1a3c7f5dc.png)

![image](https://user-images.githubusercontent.com/22342596/40734220-673498c8-6455-11e8-89d4-805ca79ac355.png)

You can see the difference in color here

![image](https://user-images.githubusercontent.com/22342596/40734290-9c0c5d56-6455-11e8-9c71-61c5b4f33f6d.png)

![image](https://user-images.githubusercontent.com/22342596/40734300-a2c491ea-6455-11e8-8d62-34bec645ae1f.png)

you can see that there are filters in Rinno app but in shiny I have removed filters.

and the worst of them all
![image](https://user-images.githubusercontent.com/22342596/40734339-c41ee7be-6455-11e8-84a6-a2a59511150d.png)
![image](https://user-images.githubusercontent.com/22342596/40734352-ca9a093e-6455-11e8-90f0-9ff558d32ae9.png)

It doesn't even have a DT table. Which I need. at first I thought there must be something wrong with my code but when I inspect it I see that I have divided that page into 4 and 8 columns and the DT id is there but it doesn't show it.

![image](https://user-images.githubusercontent.com/22342596/40734419-083bba1c-6456-11e8-9d0f-9b0cf0d276aa.png)

I have uploaded the same project roughly the same in github account. Please let me know if there is something I am supposed to do that I am not doing correctly or if there is any bug in the app itself.

https://github.com/vikram-rawat/shinyDashboard1

Please do reply

**Comment by chasemc** [comment]
The pictures are good, but try using the same browser for the comparisons. Your RInno app seems to be running in Chrome, but the "correct" examples are displayed in RStudio's browser.

**Comment by vikram-rawat** [comment]
This is the screenshot in chrome too. If you need anything else I will provide you tommarow for sure.

![image](https://user-images.githubusercontent.com/22342596/40740857-8c1ab98a-6467-11e8-8ea4-6a340083b19a.png)

**Comment by vikram-rawat** [comment]
Chrome runs every example exactly the same as in Rstudio. But Rinno has some differences.

**Comment by Dripdrop12** [comment]
This might be due to the fact that RInno is running Chrome in app-mode. We just rolled back that feature in the development branch. Can you take a look at that and see if it helps?

**Comment by vikram-rawat** [comment]
I just reinstalled the Rinno library and recreated the app. Somehow it doesn't work either. it still doesn't show me DT package.

![image](https://user-images.githubusercontent.com/22342596/40856992-61685f26-65f7-11e8-9c20-e64f3acdf906.png)


it still has a DT package but doesn't use it.

**Comment by vikram-rawat** [comment]
tell me if there is any way I can share the app with you so you can check what's the issue is? i can share it through google drive

**Comment by Dripdrop12** [comment]
That would work. From a technical standpoint, there is no reason why DT would perform differently in a RInno installation vs. running it locally. They are pretty much the same thing
