### ISSUE TITLE
Windows Defender SmartScreen Error

### ISSUE THREAD

**Issue by deepanshu88** [ficonsulting/RInno#84]
First of all. I would like to thank you for creating wonderful package. 
For some of the Win10 users, it returns error "Windows Defender SmartScreen prevented an unrecognized app error" while installing the app. To make it work, one has to turnoff the security from settings.

**Comment by Dripdrop12** [comment]
There will always be some customization required to make an application work with your security software. Inno Setup has support for code signing tools, which can also help make your app look less suspicious and lead to a more seamless integration between your app and the virus protection software you use ;)
