### ISSUE TITLE
Cant install depended packages

### ISSUE THREAD

**Issue by JK87iab** [ficonsulting/RInno#85]
Hi,
I am using Rinno 0.2.1

After compiling and running the installer on a different machine without R it returns following error:
```
library paths:
... C:/Users/Jonas/Documents/Mop/library
... C:/Program Files/R/R-3.5.0/library
working path:
... C:/Users/Jonas/Documents/Mop 

interactive R session:
... FALSE
ensuring packages: shiny, shinydashboard, DT, tidyverse, pool, odbc, config
Installation failed: formal argument "dependencies" matched by multiple actual arguments
Startup failed with error(s):

there is no package called 'shiny'
``` 

To build the installer:
```
create_app(app_name = "Mop",
          pkgs = c("shiny","shinydashboard","DT","tidyverse","pool","odbc","config"),
          include_R = T, include_Chrome = T,include_Rtools= T,
          publisher = "test")

compile_iss()
```

**Comment by Tebatu** [comment]
I have the same issue and the same error. 
```
interactive R session:
... FALSE
ensuring packages: shiny, jsonlite, httr, DT, purrr

Attaching package: 'shiny'

The following object is masked from 'package:jsonlite':

    validate

shiny installed

jsonlite installed

Skipping install of 'httr' from a cran remote, the SHA1 (1.3.1) has not changed since last install.
  Use `force = TRUE` to force installation
httr installed

Installation failed: formal argument "dependencies" matched by multiple actual arguments
Startup failed with error(s):

there is no package called 'DT'
```

I installed the shiny app in a windows 7 sandbox with a clean installation of R. 
The problem might be connected to the default library path, since when I manually installed the shiny package in R using admin rights the app did not have problems with the 'shiny' package anymore as in case of @JK87iab, but now had an error with the next specified package in `pkgs`, namely 'DT'.

**Comment by Tebatu** [comment]
I see a similar problem in https://github.com/ficonsulting/RInno/issues/81
I created an app with the code supplied in the thread and followed the instructions of @Dripdrop12 .
But the error is still coming when loading packages on the app startup.

**Comment by Tebatu** [comment]
The error disappeared when the installation is built using RInno 0.1.2 which I installed from here: https://github.com/ficonsulting/RInno/releases/tag/0.1.2
I ran, for example, the included example app plus some random packages to be installed:
```
# Example app included with RInno package
example_app(wd = getwd())

# Build an installer
create_app(app_name = "Your appname3", app_dir = "app", 
           pkgs = c("DT", "purrr", "tidyr", "tibble","dplyr","readr", "stringr", "shinythemes","readxl")
           )
compile_iss()
```

All the subsequent versions throw other errors or the latest RInno version throws the described missing package error.

**Comment by Dripdrop12** [comment]
I think this is a `devtools` bug - https://github.com/r-lib/devtools/issues/1805

I'm going to role back the use of `install_cran` until it is resolved. @chasemc do you agree?

**Comment by Dripdrop12** [comment]
Swapped `install_cran` out - d446df4f134713801766987a3de7bd626bb98ac9
