### ISSUE TITLE
Rtools 3.5 not working

### ISSUE THREAD

**Issue by JK87iab** [ficonsulting/RInno#86]
Hi, I install Rtools 3.5 with R 3.5.0 but get following error:

```Downloading package from url: http://cran.rstudio.com/src/contrib/Archive/odbc/odbc_1.1.5.tar.gz
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.5.0 was found. (Only the following incompatible version(s) of Rtools were found:3.5)
```

But of course 3.5 should work with R 3.5.0

Is this related to devtools?

[find_rtools() doesn't recognize Rtools 3.5 in R 3.5.0](https://github.com/r-lib/devtools/issues/1772)

**Comment by Dripdrop12** [comment]
It looks like that is the case. I'll try to follow that thread and make updates to RInno accordingly.
