### ISSUE TITLE
creating vignettes ... ERROR

### ISSUE THREAD

**Issue by Raguetti** [ficonsulting/RInno#90]
Hi, I have trouble installing the package. May you help me?
I don't have a lot of experience

![giterror](https://user-images.githubusercontent.com/42577887/44405004-8876eb00-a558-11e8-8737-358e8c20a932.JPG)

**Comment by Dripdrop12** [comment]
Can you translate that error message? My French is about 15 years rusty and what only good for passing the NY State Regents exam... ;)

**Comment by Raguetti** [comment]
I succesfuly installed it by changing : "build_vignettes = FALSE"

Now I can compile my applications but they can't be launched, there are mistakes with the path
It can't figure out where all it's element are. I am trying to correct it manually.

I don't know the "Vignettes" purpose. Is it related?

**Comment by Dripdrop12** [comment]
Nope. The vignettes sometimes fail because of pdf command line utilities, but they should not affect anything else.

Can you provide some more detail about your `create_app` call and the location/structure of your shiny app?
