### ISSUE TITLE
Require minimal supported R version

### ISSUE THREAD

**Issue by trybik** [ficonsulting/RInno#93]
Reason: devtools requires R >= 3.0.2 since version 1.5, and R >= 2.15 for version 1.4.x (cf. https://github.com/r-lib/devtools/releases?after=v1.6 ).

It seems best to require R >= 3.0.2. in `R_version` arg of `get_R` function rather than test and make current code compatible with archaic versions of R and devtools (cf. pkg installation commands).

**Comment by Dripdrop12** [comment]
agreed
