### ISSUE TITLE
[electron variant] node path bug

### ISSUE THREAD

**Issue by trybik** [ficonsulting/RInno#96]
Hi, just tried out the devel branch Electron variant and got some dull error after pkgs are loaded using the `package_manager.R`:
![screen shot 2018-09-10 at 18 20 27](https://user-images.githubusercontent.com/207456/45310509-baabb500-b526-11e8-98b9-fefce853031a.png)

This is due to not having npm on the path after installing it via `create_app` call (I believe there is no check after installation, only before).

I've edited env var `PATH` manually to contain "C:\Program Files\nodejs", re-run the `create_app` + `compile_iss` and voilà!

Will test it on production machine and provide some feedback.

**Comment by Dripdrop12** [comment]
Thanks @trybik! You are a trailblazer on this ;)
